### ISSUE TITLE
Doesn't work when using Rails js from 'jquery-rails'

### ISSUE THREAD

**Issue by cexposito** [iwasrobbed/Rails3-S3-Uploader-Plupload#2]
It works when you use the following javascript line in your layout file:

  <%= javascript_include_tag 'jquery-1.5.js', 'plupload/plupload.full' %>

But it stops working when you use the javascripts that are installed when you install the 'jquery-rails' gem is installed which is will be standard in Rails 3.1

<%= javascript_include_tag 'jquery', 'jquery-ui', 'jquery_ujs.js', 'application.js', 'plupload/plupload.full' %>

I have installed wireshark to try to debug it, there is no xml messaging occuring. It would appear to be a javascript issue that requires some debugging to determine the issue

Carlos

**Comment by iwasrobbed** [comment]
Sounds like something has changed in the jQuery library file.  Have you tried using Firebug or the Google Chrome Inspector to see what javascript errors it is throwing?  Typically if there is a bad enough javascript error, none of the javascript on the entire page will work.  If it's not that bad, then it will fail silently and you'll have to place `console.log` statements in the js code to debug it.

Keep in mind, the only time you should need WireShark is when you are uploading and the Flash uploader fails for some reason (S3 policy error, etc).  You need to get the uploader working first before you'll need that at all.

**Comment by cexposito** [comment]
Thanks for the tips

I found the problem you need to modify the following code, it appears that show method does not call uploader.start()

```
        // start the uploader after the progress bar shows
        $('#progress_bar').show(function () {               
          uploader.start();
```

If you change the code to the following it works, but the page displays two progress bars (one grey, and the other one red)

```
    $('#progress_bar').show();
    uploader.start();
```

Carlos

**Comment by iwasrobbed** [comment]
If `#progress_bar` exists on the page, it _should_ call it correctly.  Otherwise, the callback within `$('#progress_bar').show(function () {` never gets called since that element wasn't found and therefore could not be shown.

Glad you figured it out!

**Comment by cexposito** [comment]
#progress_bar does exist and the following code works (but there are two progress bars)

   $('#progress_bar').show(uploader.start());

I'm trying to figure out why the show method doesn't work when a function definition is passed in

   $('#progress_bar').show(function () {  
          uploader.start();
    });

**Comment by iwasrobbed** [comment]
Are you saying that you have two elements on your page that both have the same ID of `progress_bar`?  If so, jQuery ID selectors work by finding the very first `#progress_bar` on the page and ignoring all others.  The HTML5 spec says that elements denoted by ID's (such as `#progress bar`) should be unique to the page.  If you want two or more elements to have the name `progress_bar`, then you need to create unique ID names for each progress bar such as `progress_bar_1`, `progress_bar_2`, etc.

Also, try this:

```
$('#progress_bar').show('fast', function () {               
      uploader.start();
});
```

where I just added `'fast'` into the `show` method.  More info: http://api.jquery.com/show/

**Comment by cexposito** [comment]
Thanks for your help,

I only have one <div> in my page,

```
  <div class="ui-progress-bar" id="progress_bar">
    <div class="ui-progress" style="width: 1%;"><span class="ui-label" style="display:none;"></span></div>
  </div>
```

Adding 'fast' to the show method (as per your suggestion) solved the issue :)

**Comment by iwasrobbed** [comment]
Glad to hear it, I'll update the project.  Thanks for your patience :)
