### ISSUE TITLE
Fantastic! Does it work with Rails 3.1? How does the Rails server know about the uploaded file?

### ISSUE THREAD

**Issue by suzi2000** [iwasrobbed/Rails3-S3-Uploader-Plupload#3]
I have tried this, works flawlessly and its very easy to setup!

Do you see any problems with Rails 3.1.rc4 ? I am going to try it this weekend.
Also, how would you recommend to store the uploaded files to the model ?
Should i simpy use a polymorphic asset model that stores the url to the image and the permissions ?
Also i am not sure yet how rails actually knows about the files that are uploaded, since the controller is blank

Thanks :-)

**Comment by iwasrobbed** [comment]
Hi Suzi,

Glad everything worked well for you!  
- I have not run the code using the latest Rails, so please let me know if you come across any issues.  
- As far as storing the files to the model, I think that depends on your preference.  You could create an asset table and store it there if you want, or you can simply add attributes to an existing model... it's up to you and what your app is setup like.  As far as storing information about the file, I would recommend saving the filename and the URL as separate model attributes in case your S3 directory structure changes in the future.  For our app, we have to build up secure S3 query strings (https://gist.github.com/1032395) on the fly for each uploaded object, so we just build up the path to S3.
- To tell Rails about the files after the upload, you should use the `FilesUploaded` callback within the jQuery code in `uploads_helper.rb`.  You can pass whatever model attributes you need to into the `data` section of the ajax call so you can match up the model ID with the filename.  We just generate a random SHA2 hex for the filename.  Here is a quick example:

``` javascript
// in the uploaders_helper.rb file ... place this after the FilesAdded and FilesRemoved methods
//
// You need to declare some encoded_filename to give the object and then create a success_response_path in your routes
//

FileUploaded: function(up, file, info) {
// notify server of new file
  $.ajax({
    data: { 
          'filename':'#{encoded_filename}',
          'some_model_id': '#{model.id}',
          '#{request_forgery_protection_token}':'#{form_authenticity_token}'
    },
    type: 'PUT',
    url: '#{success_response_path}',
    success: function (json) {
          // return a success message from the server
          $('span.ui-label').text(json.success_message); 
          $('#progress_bar .ui-progress').addClass('success');
    },
    error: function (response) {
          // Keep in mind this is a basic example.  You should probably create a quick polling function to try this
          // ajax request again if it fails the first time.

          // show failure on progress bar
          $('#progress_bar .ui-progress').css('width', '100%');
          $('span.ui-label').text('Upload Failed :(');

          // this is just a custom function we wrote that shows a dialog box to the user
          b.messageDialog('Error', 'There was an error uploading your file: We were unable to tell the server about the new file. Please e-mail us at support@our-app.com if this continues to happen.');
    }
  });
}
```

**Comment by suzi2000** [comment]
- Great, thats so cool. It is fun to customize the javascript as plain text in the helper compared to manually call all those options for a native .js
- Interesting, I guess when using the a unique filename hash  #{model_name model_id picture_number}  there is no reason to ever save something to the model, is that what you said ? In this case the corresponding file will exist on s3 or it won't. Would there be a problem regarding the number of false file requests to s3? it will probably return something like this:

``` html
<Error>
  <Code>NoSuchKey</Code>
  <Message>The resource you requested does not exist</Message>
  <Resource>/mybucket/myfoto.jpg</Resource> 
  <RequestId>4442587FB7D0A2F9</RequestId>
</Error>
```

Great stuff, i think i throw paperclip out :)

**Comment by iwasrobbed** [comment]
- It is definitely easier to modify the JS in the helper, but keep in mind to only use an apostrophe `'` in that area and never a quotation `"` since that block of javascript is a string surrounded by quotes that gets placed into the view when the page is loaded.
- It is up to you whether or not you want to save the filename to the model.  I would recommend that you just store the filename in the model in case your app structure changes in the future.  That way, you can just go into the Rails console and ask the model object what the filename is on S3 without having to generate the hash yourself.  You can generate a unique filename when that helper is loaded using something like this:

``` ruby
    def unique_filename_for_upload
      loop do
        random_token = Digest::SHA2.hexdigest("#{Time.now.utc}--#{some_model.id.to_s}").first(20)
        break random_token unless Asset.where(:image_filename => random_token).exists?
      end
    end
```

Generally, Amazon will return an "AccessDenied" xml code if it can't find the file (at least for my bucket it does).  

``` xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>05D90177F3C5DAE5</RequestId>
  <HostId>
    80QgHdsMvxfRyzj1YT8bg2K2R2Wv32dTUyyWVVYCNekk2r6Qy2NGcklq5tK07xKE
  </HostId>
</Error>
```

**Comment by suzi2000** [comment]
cool, thanks :) The way you modify the js is very cool i have never seen that before

by the way, i also found the :fingerprint from paperclip interesting. while its supposed to optimize browser caching, it also claims to validate the image integrity. so the link only expires when the asset changes
https://github.com/thoughtbot/paperclip/issues/224
