### ISSUE TITLE
AWS & HTML5?

### ISSUE THREAD

**Issue by marcandre** [iwasrobbed/Rails3-S3-Uploader-Plupload#6]
Hi!
The readme states that AWS does not support HTML5 upload and links to a long thread. Is it possible that the issue has been fixed on AWS? Check the last page of the thread: https://forums.aws.amazon.com/thread.jspa?threadID=34281&start=275&tstart=0#jive-message-432822

**Comment by iwasrobbed** [comment]
Yes, the issue has since been fixed.  This README is just outdated since the repo was created a couple of years ago.
